### PR TITLE
Addition of Hindi language

### PR DESCRIPTION
**Pull request by Prasanta-Hembram**
I have translated Easy Diary in Hindi Language. I love to add one additional language Santali but it uses a little new script Ol Chiki and a non ASOP language which cannot be set from device settings but it is widely supported in Android. So i request you to please add in-app language selection with the application like  #59(Multilingual UI), so that i can help add one additional language for this very useful application.

Thanks

### CODE REVIEW

**Comment by hanjoongcho** [comment]
@Prasanta-Hembram 
First of all, thank you for participating in the Easy Diary Project translation.
I have a few questions.
Q1> The language you requested for PR is Hindi (hi_IN), one of the official languages of India, right?
Q2> And what you want additionally is the following content?
Added ability to set Santali language using Ol Chiki characters (Similar to the content of issue #59)
Q3> What is'non ASOP language'?

**Comment by Prasanta-Hembram** [comment]
> Q1> The language you requested for PR is Hindi (hi_IN), one of the official languages of India, right?
> Q2> And what you want additionally is the following content?
> Added ability to set Santali language using Ol Chiki characters (Similar to the content of issue #59)
> Q3> What is'non ASOP language'?
Sorry for not clarifying :-|>

1- Yes, correct hi_HI is official language of India and this pull is for this only, rest are just my doubts.
2- Yes, Santali is also officially recognized language of India which is now written in Ol Chiki script and i am a native speaker of Santali language. It you agree then i will also proceed for translation in Santali language.
2.  Yes as shown in the figure of drop down language selection feature in #59. Actually your app supports language change from device settings only. Till now no android ROM supports this language change from System language selection, but their is reading  support and people can write as well with Ol Chiki script(Support in Gboard). This script is used to write articles in Santali Wikipedia(sat.wikipedia.org/).
3. Sorry for not clearing it, by ASOP support languages i mean by default not all android ROM supports Santali language(code-sat), infact it is never transalated or not yet added as a language selection in any ROM. So we cannot change the language of the application to Santali if i translate it then is of no use, so i was asking of any sign of adding that dropdown language selection feature within the application. If so then may i proceed to translate it in Santali language?

**Comment by Prasanta-Hembram** [comment]
Also, i clarify that Santali was used to be written in roman, devnagri script but after Pandit Raghunath Murmu invented Ol Chiki script, people widely use this script. Hindi is written in devnagri script only and is supported in almost all ROM, ex. It can be selected from device settings. The pull request i made is for Hindi language (Official language of India) only, i know both language very well. For Santali language if you agree i can also contribute. I hope i am clear:-).

**Comment by hanjoongcho** [comment]
@Prasanta-Hembram 
I understand what you want.
I still have one question.
Maybe ASOP is a typo of AOSP (Android Open Source Project)?
If it's not a typo, can you tell us the full name of ASOP?

**Comment by Prasanta-Hembram** [comment]
Many apology @hanjoongcho above ASOP is AOSP.

**Comment by hanjoongcho** [comment]
@Prasanta-Hembram 
The question was resolved.

The PR you requested will be merged immediately.
I'll add features if possible after technical review to see if it is possible to set and use languages other than the official Android language in the OS setting.

**Comment by hanjoongcho** [comment]
@Prasanta-Hembram 
Please note that the part where the LIne Break character was incorrectly entered was corrected :)
https://github.com/hanjoongcho/aaf-easydiary/commit/72d172d7412489464799e9c26b7adb5942aeb3b2

**Pull request merged**
