### PR TITLE
Add some Chinese Traditional(zh-rTW) translation.

### PR DESCRIPTION
**Pull request by ei9**

### CODE REVIEW

**Comment by hanjoongcho** [comment]
@ei9 
Thank you for participating in the translation work. 😀
However, merging the strings.xml file with only some words translated is difficult.
Merge is possible by following the procedure below.
Even if some translations are not made, the total number of lines in strings.xml for all languages must be the same (852 lines).


01. Copy the file in the path /app/src/main/res/values-zh-rCN/strings.xml
02. Create /app/src/main/res/values-zh-rTW/strings.xml file
03. Edit the translated words among the words in the /app/src/main/res/values-zh-rTW/strings.xml file and request PR

Is it possible?

**Comment by ei9** [comment]
I am sorry. But Nope. XD
Cause they are different actually.
Maybe I can complete the translation then make the merge possible.
Thanks!

**Comment by hanjoongcho** [comment]
@ei9 
Thanks for the confirmation, and I'll explain a little bit more in the hopes that it will be helpful.
I understand that the zh-rCN language and the zh-rTW language are actually different. 😃
However, if the translation is not completed, the language to be used by zh-rCN is required by default, so I requested that you select one of the previously translated languages and match the total number of lines (852 lines).
It is not necessary to set zh-rCN as the default.
If you want to express untranslated key values in English, you can use values-en and apply only some items (translated items).

**Comment by ei9** [comment]
I see.
Thank you.

**Pull request closed without merging**
